File : dejima - prototype - master / docker - compose . yml

peera-db:
    image : dejima - stretch - db
    container_name : PeerA - db
    ports:
        - 54321:5432
    volumes:
        - ./db/postgresql.conf:/etc/postgresql.conf
        - ./db/initialize.sh:/docker-entrypoint-initdb.d/initialize.sh
        - ./db/setup_files:/etc/setup_files
    environment:
    - POSTGRES_PASSWORD = postgres
    - PEER_NAME = PeerA
    - DEJIMA_EXECUTION_ENDPOINT = PeerA - proxy :8000/ execute
    - DEJIMA_TERMINATION_ENDPOINT = PeerA - proxy :8000/ terminate
    networks:
        dejima_net:
            ipv4_address: 172.30.0.3
            
mediator - db :
    image : dejima - stretch - db
    container_name : Mediator - db
    ports :
    - 54323:5432
volumes :
- ./ db / postgresql . conf :/ etc / postgresql . conf
- ./ db / initialize . sh :/ docker - entrypoint - initdb .d/ initialize . sh
- ./ db / setup_files :/ etc / setup_files
environment :
- POSTGRES_PASSWORD = postgres
- PEER_NAME = Mediator
- DEJIMA_EXECUTION_ENDPOINT = Mediator - proxy :8000/ execute
- DEJIMA_TERMINATION_ENDPOINT = Mediator - proxy :8000/ terminate

networks :
dejima_net :
ipv4_address : 172.30.0.9
            

 
